// Code generated by wacogo-witgen from engine.wit. DO NOT EDIT.

// Package workflowengine provides Go bindings for the flower:engine/workflow-engine interface.
package workflowengine

import (
	"context"
	"fmt"

	"github.com/partite-ai/wacogo"
	"github.com/partite-ai/wacogo/host"
)

// workflowEngineWrapper is the concrete type returned by WrapInstance
// as a WorkflowEngine. Held internally; users hold it via the WorkflowEngine
// interface.
type workflowEngineWrapper struct {
	callerInst   *host.ComponentInstance
	fnCompile    *host.ExportedFunc
	fnTransition *host.ExportedFunc
}

// WrapInstance returns a WorkflowEngine that forwards method calls to
// callee. caller is a Factory-built host instance whose state hosts any
// handles minted by callee during those calls.
func WrapInstance(caller *host.ComponentInstance, callee *wacogo.ComponentInstance) WorkflowEngine {
	w_ := &workflowEngineWrapper{callerInst: caller}
	w_.fnCompile = host.WrapExportedFunc(callee.ExportedFunc("compile"))
	w_.fnTransition = host.WrapExportedFunc(callee.ExportedFunc("transition"))
	return w_
}
func (w *workflowEngineWrapper) Compile(ctx context.Context, definition WorkflowDefinition) (ResultExecutableWorkflowPlanListDiagnostic, error) {
	var resVal_ ResultExecutableWorkflowPlanListDiagnostic
	var resErr_ error
	arg0_ := definition
	{
		callErr_ := w.fnCompile.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				if err_ := lowerFlatWorkflowDefinition(ctx, caller, callee, w.callerInst, w.fnCompile.ParamType(0), stack[0:6], arg0_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemResultExecutableWorkflowPlanListDiagnostic(ctx, caller, callee, w.callerInst, w.fnCompile.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}

func (w *workflowEngineWrapper) Transition(ctx context.Context, plan ExecutableWorkflowPlan, snapshot OptionExecutionSnapshot, event ExecutionEvent) (ResultTransitionResultEngineError, error) {
	var resVal_ ResultTransitionResultEngineError
	var resErr_ error
	arg0_ := plan
	arg1_ := snapshot
	arg2_ := event
	{
		callErr_ := w.fnTransition.CallRaw(ctx, w.callerInst,
			func(caller, callee *host.CallContext, stack []uint64) {
				paramsPtr_, err_ := callee.Realloc(ctx, 0, 0, 8, 184)
				if err_ != nil {
					resErr_ = fmt.Errorf("wacogo/witgen: allocate indirect parameters: %w", err_)
					return
				}
				stack[0] = uint64(paramsPtr_)
				h := w.callerInst
				_ = h
				if err_ := lowerMemExecutableWorkflowPlan(ctx, caller, callee, h, w.fnTransition.ParamType(0), paramsPtr_+0, arg0_); err_ != nil {
					resErr_ = err_
					return
				}
				if err_ := lowerMemOptionExecutionSnapshot(ctx, caller, callee, h, w.fnTransition.ParamType(1), paramsPtr_+32, arg1_); err_ != nil {
					resErr_ = err_
					return
				}
				if err_ := lowerMemExecutionEvent(ctx, caller, callee, h, w.fnTransition.ParamType(2), paramsPtr_+120, arg2_); err_ != nil {
					resErr_ = err_
					return
				}
			},
			func(caller, callee *host.CallContext, stack []uint64) {
				if v_, err_ := liftMemResultTransitionResultEngineError(ctx, caller, callee, w.callerInst, w.fnTransition.ResultType(0), uint32(stack[0])); err_ != nil {
					resErr_ = err_
					return
				} else {
					resVal_ = v_
				}
			},
		)
		if callErr_ != nil {
			return nil, fmt.Errorf("wacogo/witgen: CallRaw failed: %w", callErr_)
		}
		if resErr_ != nil {
			return nil, resErr_
		}
	}
	return resVal_, nil
}
