// Code generated by wacogo-witgen from engine.wit. DO NOT EDIT.

// Package workflowengine provides Go bindings for the flower:engine/workflow-engine interface.
package workflowengine

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "flower:engine/workflow-engine@0.2.0"

// WorkflowEngine is the Go binding for the flower:engine/workflow-engine interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a WorkflowEngine that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type WorkflowEngine interface {
	Compile(ctx context.Context, definition WorkflowDefinition) (ResultExecutableWorkflowPlanListDiagnostic, error)
	Transition(ctx context.Context, plan ExecutableWorkflowPlan, snapshot OptionExecutionSnapshot, event ExecutionEvent) (ResultTransitionResultEngineError, error)
}

// NodeKind corresponds to the WIT enum node-kind.
type NodeKind uint8

const (
	NodeKindStart    NodeKind = 0
	NodeKindActivity NodeKind = 1
	NodeKindFinish   NodeKind = 2
)

func (v NodeKind) String() string {
	switch v {
	case NodeKindStart:
		return "start"
	case NodeKindActivity:
		return "activity"
	case NodeKindFinish:
		return "finish"
	}
	return "NodeKind(unknown)"
}

// OptionExecutionSnapshot corresponds to a WIT option<...> type.
type OptionExecutionSnapshot struct {
	IsSome bool
	Value  ExecutionSnapshot
}

func SomeExecutionSnapshot(v ExecutionSnapshot) OptionExecutionSnapshot {
	return OptionExecutionSnapshot{IsSome: true, Value: v}
}

func NoneExecutionSnapshot() OptionExecutionSnapshot {
	return OptionExecutionSnapshot{}
}

// OptionPayload corresponds to a WIT option<...> type.
type OptionPayload struct {
	IsSome bool
	Value  Payload
}

func SomePayload(v Payload) OptionPayload {
	return OptionPayload{IsSome: true, Value: v}
}

func NonePayload() OptionPayload {
	return OptionPayload{}
}

// OptionRetryPolicy corresponds to a WIT option<...> type.
type OptionRetryPolicy struct {
	IsSome bool
	Value  RetryPolicy
}

func SomeRetryPolicy(v RetryPolicy) OptionRetryPolicy {
	return OptionRetryPolicy{IsSome: true, Value: v}
}

func NoneRetryPolicy() OptionRetryPolicy {
	return OptionRetryPolicy{}
}

// OptionString corresponds to a WIT option<...> type.
type OptionString struct {
	IsSome bool
	Value  string
}

func SomeString(v string) OptionString {
	return OptionString{IsSome: true, Value: v}
}

func NoneString() OptionString {
	return OptionString{}
}

// ResultExecutableWorkflowPlanListDiagnostic corresponds to a WIT result<...> type.
type ResultExecutableWorkflowPlanListDiagnostic interface{ isResultExecutableWorkflowPlanListDiagnostic() }
type ResultExecutableWorkflowPlanListDiagnosticOk struct{ Value ExecutableWorkflowPlan }
type ResultExecutableWorkflowPlanListDiagnosticErr struct{ Value []Diagnostic }

func (ResultExecutableWorkflowPlanListDiagnosticOk) isResultExecutableWorkflowPlanListDiagnostic()  {}
func (ResultExecutableWorkflowPlanListDiagnosticErr) isResultExecutableWorkflowPlanListDiagnostic() {}

// ResultTransitionResultEngineError corresponds to a WIT result<...> type.
type ResultTransitionResultEngineError interface{ isResultTransitionResultEngineError() }
type ResultTransitionResultEngineErrorOk struct{ Value TransitionResult }
type ResultTransitionResultEngineErrorErr struct{ Value EngineError }

func (ResultTransitionResultEngineErrorOk) isResultTransitionResultEngineError()  {}
func (ResultTransitionResultEngineErrorErr) isResultTransitionResultEngineError() {}

// SpecificationVersion corresponds to the WIT record specification-version.
type SpecificationVersion struct {
	Major uint16
	Minor uint16
}

// FixedBackoff corresponds to the WIT record fixed-backoff.
type FixedBackoff struct {
	DelayMs uint64
}

// ExponentialBackoff corresponds to the WIT record exponential-backoff.
type ExponentialBackoff struct {
	InitialDelayMs uint64
	Multiplier     uint32
	MaximumDelayMs uint64
}

// RetryPolicy corresponds to the WIT record retry-policy.
type RetryPolicy struct {
	MaxAttempts           uint32
	RetryableFailureCodes []string
	Backoff               BackoffPolicy
}

// NodeDefinition corresponds to the WIT record node-definition.
type NodeDefinition struct {
	ID          string
	Kind        NodeKind
	RetryPolicy OptionRetryPolicy
}

// EdgeDefinition corresponds to the WIT record edge-definition.
type EdgeDefinition struct {
	ID     string
	Source string
	Target string
}

// WorkflowDefinition corresponds to the WIT record workflow-definition.
type WorkflowDefinition struct {
	ID    string
	Nodes []NodeDefinition
	Edges []EdgeDefinition
}

// Diagnostic corresponds to the WIT record diagnostic.
type Diagnostic struct {
	Code    string
	Message string
	Subject OptionString
}

// PlanNode corresponds to the WIT record plan-node.
type PlanNode struct {
	ID          string
	Kind        NodeKind
	RetryPolicy OptionRetryPolicy
}

// ExecutableWorkflowPlan corresponds to the WIT record executable-workflow-plan.
type ExecutableWorkflowPlan struct {
	SpecificationVersion SpecificationVersion
	WorkflowID           string
	Fingerprint          string
	Nodes                []PlanNode
}

// PlanReference corresponds to the WIT record plan-reference.
type PlanReference struct {
	SpecificationVersion SpecificationVersion
	WorkflowID           string
	Fingerprint          string
}

// Payload corresponds to the WIT record payload.
type Payload struct {
	MediaType string
	Bytes     []uint8
}

// NodeActivation corresponds to the WIT record node-activation.
type NodeActivation struct {
	ActivationID       string
	ActivationRevision uint64
	NodeID             string
	Input              Payload
}

// NodeAttempt corresponds to the WIT record node-attempt.
type NodeAttempt struct {
	AttemptID     string
	AttemptNumber uint32
	EffectID      string
}

// AttemptFailure corresponds to the WIT record attempt-failure.
type AttemptFailure struct {
	Code    string
	Details OptionPayload
}

// RetryTimer corresponds to the WIT record retry-timer.
type RetryTimer struct {
	TimerID           string
	EffectID          string
	FailedAttemptID   string
	NextAttemptNumber uint32
	DelayMs           uint64
}

// AwaitingAttempt corresponds to the WIT record awaiting-attempt.
type AwaitingAttempt struct {
	Activation NodeActivation
	Attempt    NodeAttempt
}

// WaitingForRetry corresponds to the WIT record waiting-for-retry.
type WaitingForRetry struct {
	Activation NodeActivation
	Attempt    NodeAttempt
	Failure    AttemptFailure
	Timer      RetryTimer
}

// FailedExecution corresponds to the WIT record failed-execution.
type FailedExecution struct {
	Activation NodeActivation
	Attempt    NodeAttempt
	Failure    AttemptFailure
}

// ExecutionSnapshot corresponds to the WIT record execution-snapshot.
type ExecutionSnapshot struct {
	ExecutionID   string
	PlanReference PlanReference
	Revision      uint64
	State         ExecutionState
}

// ExecutionStartedEvent corresponds to the WIT record execution-started-event.
type ExecutionStartedEvent struct {
	EventID       string
	ExecutionID   string
	PlanReference PlanReference
	Input         Payload
}

// NodeAttemptSucceededEvent corresponds to the WIT record node-attempt-succeeded-event.
type NodeAttemptSucceededEvent struct {
	EventID          string
	ExecutionID      string
	ExpectedRevision uint64
	ActivationID     string
	AttemptID        string
	AttemptNumber    uint32
	EffectID         string
	NodeID           string
	Output           Payload
}

// NodeAttemptFailedEvent corresponds to the WIT record node-attempt-failed-event.
type NodeAttemptFailedEvent struct {
	EventID          string
	ExecutionID      string
	ExpectedRevision uint64
	ActivationID     string
	AttemptID        string
	AttemptNumber    uint32
	EffectID         string
	NodeID           string
	Failure          AttemptFailure
}

// TimerFiredEvent corresponds to the WIT record timer-fired-event.
type TimerFiredEvent struct {
	EventID           string
	ExecutionID       string
	ExpectedRevision  uint64
	TimerID           string
	ActivationID      string
	NextAttemptNumber uint32
}

// ExecuteNodeAttemptEffect corresponds to the WIT record execute-node-attempt-effect.
type ExecuteNodeAttemptEffect struct {
	EffectID      string
	ActivationID  string
	AttemptID     string
	AttemptNumber uint32
	NodeID        string
	Input         Payload
}

// ScheduleTimerEffect corresponds to the WIT record schedule-timer-effect.
type ScheduleTimerEffect struct {
	EffectID          string
	TimerID           string
	ActivationID      string
	FailedAttemptID   string
	NextAttemptNumber uint32
	DelayMs           uint64
}

// TransitionResult corresponds to the WIT record transition-result.
type TransitionResult struct {
	Snapshot ExecutionSnapshot
	Effects  []ExecutionEffect
}

// EngineError corresponds to the WIT record engine-error.
type EngineError struct {
	Code    string
	Message string
}

// BackoffPolicy corresponds to the WIT variant backoff-policy. Sealed:
// only the case structs below satisfy this interface.
type BackoffPolicy interface{ isBackoffPolicy() }

// BackoffPolicyNone is the "none" case of BackoffPolicy.
type BackoffPolicyNone struct {
}

func (BackoffPolicyNone) isBackoffPolicy() {}

// BackoffPolicyFixed is the "fixed" case of BackoffPolicy.
type BackoffPolicyFixed struct {
	Value FixedBackoff
}

func (BackoffPolicyFixed) isBackoffPolicy() {}

// BackoffPolicyExponential is the "exponential" case of BackoffPolicy.
type BackoffPolicyExponential struct {
	Value ExponentialBackoff
}

func (BackoffPolicyExponential) isBackoffPolicy() {}

// ExecutionState corresponds to the WIT variant execution-state. Sealed:
// only the case structs below satisfy this interface.
type ExecutionState interface{ isExecutionState() }

// ExecutionStateAwaitingAttempt is the "awaiting-attempt" case of ExecutionState.
type ExecutionStateAwaitingAttempt struct {
	Value AwaitingAttempt
}

func (ExecutionStateAwaitingAttempt) isExecutionState() {}

// ExecutionStateWaitingForRetry is the "waiting-for-retry" case of ExecutionState.
type ExecutionStateWaitingForRetry struct {
	Value WaitingForRetry
}

func (ExecutionStateWaitingForRetry) isExecutionState() {}

// ExecutionStateCompleted is the "completed" case of ExecutionState.
type ExecutionStateCompleted struct {
	Value Payload
}

func (ExecutionStateCompleted) isExecutionState() {}

// ExecutionStateFailed is the "failed" case of ExecutionState.
type ExecutionStateFailed struct {
	Value FailedExecution
}

func (ExecutionStateFailed) isExecutionState() {}

// ExecutionEvent corresponds to the WIT variant execution-event. Sealed:
// only the case structs below satisfy this interface.
type ExecutionEvent interface{ isExecutionEvent() }

// ExecutionEventExecutionStarted is the "execution-started" case of ExecutionEvent.
type ExecutionEventExecutionStarted struct {
	Value ExecutionStartedEvent
}

func (ExecutionEventExecutionStarted) isExecutionEvent() {}

// ExecutionEventNodeAttemptSucceeded is the "node-attempt-succeeded" case of ExecutionEvent.
type ExecutionEventNodeAttemptSucceeded struct {
	Value NodeAttemptSucceededEvent
}

func (ExecutionEventNodeAttemptSucceeded) isExecutionEvent() {}

// ExecutionEventNodeAttemptFailed is the "node-attempt-failed" case of ExecutionEvent.
type ExecutionEventNodeAttemptFailed struct {
	Value NodeAttemptFailedEvent
}

func (ExecutionEventNodeAttemptFailed) isExecutionEvent() {}

// ExecutionEventTimerFired is the "timer-fired" case of ExecutionEvent.
type ExecutionEventTimerFired struct {
	Value TimerFiredEvent
}

func (ExecutionEventTimerFired) isExecutionEvent() {}

// ExecutionEffect corresponds to the WIT variant execution-effect. Sealed:
// only the case structs below satisfy this interface.
type ExecutionEffect interface{ isExecutionEffect() }

// ExecutionEffectExecuteNodeAttempt is the "execute-node-attempt" case of ExecutionEffect.
type ExecutionEffectExecuteNodeAttempt struct {
	Value ExecuteNodeAttemptEffect
}

func (ExecutionEffectExecuteNodeAttempt) isExecutionEffect() {}

// ExecutionEffectScheduleTimer is the "schedule-timer" case of ExecutionEffect.
type ExecutionEffectScheduleTimer struct {
	Value ScheduleTimerEffect
}

func (ExecutionEffectScheduleTimer) isExecutionEffect() {}
