// Code generated by wacogo-witgen from engine.wit. DO NOT EDIT.

// Package workflowengine provides Go bindings for the flower:engine/workflow-engine interface.
package workflowengine

import (
	"context"
)

// InterfaceName is the canonical WIT id of the interface this binding
// was generated from.
const InterfaceName = "flower:engine/workflow-engine@0.1.0"

// WorkflowEngine is the Go binding for the flower:engine/workflow-engine interface.
// Implement it to provide a host-side component, or pass an exported wasm
// instance to WrapInstance to obtain a WorkflowEngine that calls into wasm.
// Resource-typed parameters and results appear as *<R>Handle values that can
// be passed across component boundaries.
type WorkflowEngine interface {
	Compile(ctx context.Context, definition WorkflowDefinition) (ResultExecutableWorkflowPlanListDiagnostic, error)
	Transition(ctx context.Context, plan ExecutableWorkflowPlan, snapshot OptionExecutionSnapshot, event ExecutionEvent) (ResultTransitionResultEngineError, error)
}

// NodeKind corresponds to the WIT enum node-kind.
type NodeKind uint8

const (
	NodeKindStart    NodeKind = 0
	NodeKindActivity NodeKind = 1
	NodeKindFinish   NodeKind = 2
)

func (v NodeKind) String() string {
	switch v {
	case NodeKindStart:
		return "start"
	case NodeKindActivity:
		return "activity"
	case NodeKindFinish:
		return "finish"
	}
	return "NodeKind(unknown)"
}

// OptionExecutionSnapshot corresponds to a WIT option<...> type.
type OptionExecutionSnapshot struct {
	IsSome bool
	Value  ExecutionSnapshot
}

func SomeExecutionSnapshot(v ExecutionSnapshot) OptionExecutionSnapshot {
	return OptionExecutionSnapshot{IsSome: true, Value: v}
}

func NoneExecutionSnapshot() OptionExecutionSnapshot {
	return OptionExecutionSnapshot{}
}

// OptionString corresponds to a WIT option<...> type.
type OptionString struct {
	IsSome bool
	Value  string
}

func SomeString(v string) OptionString {
	return OptionString{IsSome: true, Value: v}
}

func NoneString() OptionString {
	return OptionString{}
}

// ResultExecutableWorkflowPlanListDiagnostic corresponds to a WIT result<...> type.
type ResultExecutableWorkflowPlanListDiagnostic interface{ isResultExecutableWorkflowPlanListDiagnostic() }
type ResultExecutableWorkflowPlanListDiagnosticOk struct{ Value ExecutableWorkflowPlan }
type ResultExecutableWorkflowPlanListDiagnosticErr struct{ Value []Diagnostic }

func (ResultExecutableWorkflowPlanListDiagnosticOk) isResultExecutableWorkflowPlanListDiagnostic()  {}
func (ResultExecutableWorkflowPlanListDiagnosticErr) isResultExecutableWorkflowPlanListDiagnostic() {}

// ResultTransitionResultEngineError corresponds to a WIT result<...> type.
type ResultTransitionResultEngineError interface{ isResultTransitionResultEngineError() }
type ResultTransitionResultEngineErrorOk struct{ Value TransitionResult }
type ResultTransitionResultEngineErrorErr struct{ Value EngineError }

func (ResultTransitionResultEngineErrorOk) isResultTransitionResultEngineError()  {}
func (ResultTransitionResultEngineErrorErr) isResultTransitionResultEngineError() {}

// SpecificationVersion corresponds to the WIT record specification-version.
type SpecificationVersion struct {
	Major uint16
	Minor uint16
}

// NodeDefinition corresponds to the WIT record node-definition.
type NodeDefinition struct {
	ID   string
	Kind NodeKind
}

// EdgeDefinition corresponds to the WIT record edge-definition.
type EdgeDefinition struct {
	ID     string
	Source string
	Target string
}

// WorkflowDefinition corresponds to the WIT record workflow-definition.
type WorkflowDefinition struct {
	ID    string
	Nodes []NodeDefinition
	Edges []EdgeDefinition
}

// Diagnostic corresponds to the WIT record diagnostic.
type Diagnostic struct {
	Code    string
	Message string
	Subject OptionString
}

// PlanNode corresponds to the WIT record plan-node.
type PlanNode struct {
	ID   string
	Kind NodeKind
}

// ExecutableWorkflowPlan corresponds to the WIT record executable-workflow-plan.
type ExecutableWorkflowPlan struct {
	SpecificationVersion SpecificationVersion
	WorkflowID           string
	Fingerprint          string
	Nodes                []PlanNode
}

// PlanReference corresponds to the WIT record plan-reference.
type PlanReference struct {
	SpecificationVersion SpecificationVersion
	WorkflowID           string
	Fingerprint          string
}

// Payload corresponds to the WIT record payload.
type Payload struct {
	MediaType string
	Bytes     []uint8
}

// AwaitingNode corresponds to the WIT record awaiting-node.
type AwaitingNode struct {
	NodeID   string
	EffectID string
	Input    Payload
}

// ExecutionSnapshot corresponds to the WIT record execution-snapshot.
type ExecutionSnapshot struct {
	ExecutionID   string
	PlanReference PlanReference
	Revision      uint64
	State         ExecutionState
}

// ExecutionStartedEvent corresponds to the WIT record execution-started-event.
type ExecutionStartedEvent struct {
	EventID       string
	ExecutionID   string
	PlanReference PlanReference
	Input         Payload
}

// NodeCompletedEvent corresponds to the WIT record node-completed-event.
type NodeCompletedEvent struct {
	EventID          string
	ExecutionID      string
	ExpectedRevision uint64
	EffectID         string
	NodeID           string
	Output           Payload
}

// ExecuteNodeEffect corresponds to the WIT record execute-node-effect.
type ExecuteNodeEffect struct {
	EffectID    string
	ExecutionID string
	NodeID      string
	Input       Payload
}

// TransitionResult corresponds to the WIT record transition-result.
type TransitionResult struct {
	Snapshot ExecutionSnapshot
	Effects  []ExecutionEffect
}

// EngineError corresponds to the WIT record engine-error.
type EngineError struct {
	Code    string
	Message string
}

// ExecutionState corresponds to the WIT variant execution-state. Sealed:
// only the case structs below satisfy this interface.
type ExecutionState interface{ isExecutionState() }

// ExecutionStateAwaitingNode is the "awaiting-node" case of ExecutionState.
type ExecutionStateAwaitingNode struct {
	Value AwaitingNode
}

func (ExecutionStateAwaitingNode) isExecutionState() {}

// ExecutionStateCompleted is the "completed" case of ExecutionState.
type ExecutionStateCompleted struct {
	Value Payload
}

func (ExecutionStateCompleted) isExecutionState() {}

// ExecutionEvent corresponds to the WIT variant execution-event. Sealed:
// only the case structs below satisfy this interface.
type ExecutionEvent interface{ isExecutionEvent() }

// ExecutionEventExecutionStarted is the "execution-started" case of ExecutionEvent.
type ExecutionEventExecutionStarted struct {
	Value ExecutionStartedEvent
}

func (ExecutionEventExecutionStarted) isExecutionEvent() {}

// ExecutionEventNodeCompleted is the "node-completed" case of ExecutionEvent.
type ExecutionEventNodeCompleted struct {
	Value NodeCompletedEvent
}

func (ExecutionEventNodeCompleted) isExecutionEvent() {}

// ExecutionEffect corresponds to the WIT variant execution-effect. Sealed:
// only the case structs below satisfy this interface.
type ExecutionEffect interface{ isExecutionEffect() }

// ExecutionEffectExecuteNode is the "execute-node" case of ExecutionEffect.
type ExecutionEffectExecuteNode struct {
	Value ExecuteNodeEffect
}

func (ExecutionEffectExecuteNode) isExecutionEffect() {}
