[package]
name = "flower-conformance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flower-compiler = { path = "../flower-compiler" }
flower-kernel = { path = "../flower-kernel" }
flower-plan = { path = "../flower-plan" }
serde.workspace = true
serde_json.workspace = true
